name: Rust build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  minimal-setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  full-setup:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly]

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        profile: minimal
        override: true
        components: rustfmt, clippy

    - name: Build (nightly)
      run: cargo +${{ matrix.toolchain }} build --all-features --verbose
    - name: Run tests (nightly)
      run: cargo +${{ matrix.toolchain }} test --all-features --verbose
